### ISSUE TITLE
Doesn't seem to work in Bun

### ISSUE THREAD

**Issue by Blankeos** [vitejs/vite-plugin-basic-ssl#48]
I'll try to make a repro when I can, but currently getting this error whenever I run Vite using Bun.

`    "dev": "bunx --bun vite --host" `

The error: 

```sh
│ Failed to find Response internal state key
│ error when starting dev server:
│ ENAMETOOLONG: File name too long
│     at readFile (native)
│     at /Users/carlo/Desktop/Projects/_temp/elysia-cors-bug/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:46111:15
│     at readFileIfExists (/Users/carlo/Desktop/Projects/_temp/elysia-cors-bug/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:46109:32)
│     at /Users/carlo/Desktop/Projects/_temp/elysia-cors-bug/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:46103:4
│     at resolveHttpsConfig (/Users/carlo/Desktop/Projects/_temp/elysia-cors-bug/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:46099:34)
│     at /Users/carlo/Desktop/Projects/_temp/elysia-cors-bug/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:63051:29
│     at processTicksAndRejections (:12:39)
```

----

It works fine with node though:

`    "dev": "vite --host" `

**Comment by bluwy** [comment]
A Bun-only bug should be reported to Bun.
