### ISSUE TITLE
init.headers is a symbol, which cannot be converted to a DOMString

### ISSUE THREAD

**Issue by khromov** [vitejs/vite-plugin-basic-ssl#53]
When installing in a brand new [SvelteKit 2 project](https://kit.svelte.dev/docs/creating-a-project) using  VITE v5.4.8, the following error is displayed when trying to navigate to a page:

```
TypeError: Request constructor: init.headers is a symbol, which cannot be converted to a DOMString.
    at webidl.errors.exception (node:internal/deps/undici/undici:3384:14)
    at webidl.converters.DOMString (node:internal/deps/undici/undici:3650:29)
    at webidl.converters.ByteString (node:internal/deps/undici/undici:3658:35)
    at Object.record<ByteString, ByteString> (node:internal/deps/undici/undici:3567:30)
    at webidl.converters.HeadersInit (node:internal/deps/undici/undici:8715:67)
    at Object.RequestInit (node:internal/deps/undici/undici:3624:21)
    at new Request (node:internal/deps/undici/undici:9267:34)
    at getRequest (file:///Users/k/Documents/GitHub/a/node_modules/@sveltejs/kit/src/exports/node/index.js:109:9)
    at file:///Users/k/Documents/GitHub/a/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:498:27
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

Vite config:

```ts
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vitest/config';

import basicSsl from '@vitejs/plugin-basic-ssl';

export default defineConfig({
	plugins: [basicSsl(), sveltekit()],
	test: {
		include: ['src/**/*.{test,spec}.{js,ts}']
	}
});

```

**Comment by benmccann** [comment]
Can you try again with the latest SvelteKit?

**Comment by khromov** [comment]
It works when creating a brand new project with `npx sv create`. Thanks! 🙇
